// Code generated by go-web3/abigen. DO NOT EDIT.
// Hash: b5b5ed9be96940b7b9def84dade68d64a1502cea00ce8c6a1ed8ca98d58fa913
package erc1155

import (
	"fmt"
	"math/big"

	web3 "github.com/umbracle/go-web3"
	"github.com/umbracle/go-web3/contract"
	"github.com/umbracle/go-web3/jsonrpc"
)

var (
	_ = big.NewInt
)

// ERC1155 is a solidity contract
type ERC1155 struct {
	c *contract.Contract
}

// NewERC1155 creates a new instance of the contract at a specific address
func NewERC1155(addr web3.Address, provider *jsonrpc.Client) *ERC1155 {
	return &ERC1155{c: contract.NewContract(addr, abiERC1155, provider)}
}

// Contract returns the contract object
func (e *ERC1155) Contract() *contract.Contract {
	return e.c
}

// calls

// BalanceOf calls the balanceOf method in the solidity contract
func (e *ERC1155) BalanceOf(account web3.Address, id *big.Int, block ...web3.BlockNumber) (retval0 *big.Int, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("balanceOf", web3.EncodeBlock(block...), account, id)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(*big.Int)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// BalanceOfBatch calls the balanceOfBatch method in the solidity contract
func (e *ERC1155) BalanceOfBatch(accounts []web3.Address, ids []*big.Int, block ...web3.BlockNumber) (retval0 []*big.Int, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("balanceOfBatch", web3.EncodeBlock(block...), accounts, ids)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].([]*big.Int)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// IsApprovedForAll calls the isApprovedForAll method in the solidity contract
func (e *ERC1155) IsApprovedForAll(account web3.Address, operator web3.Address, block ...web3.BlockNumber) (retval0 bool, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("isApprovedForAll", web3.EncodeBlock(block...), account, operator)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(bool)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// SupportsInterface calls the supportsInterface method in the solidity contract
func (e *ERC1155) SupportsInterface(interfaceId [4]byte, block ...web3.BlockNumber) (retval0 bool, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("supportsInterface", web3.EncodeBlock(block...), interfaceId)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(bool)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// Uri calls the uri method in the solidity contract
func (e *ERC1155) Uri(val0 *big.Int, block ...web3.BlockNumber) (retval0 string, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("uri", web3.EncodeBlock(block...), val0)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(string)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// txns

// SafeBatchTransferFrom sends a safeBatchTransferFrom transaction in the solidity contract
func (e *ERC1155) SafeBatchTransferFrom(from web3.Address, to web3.Address, ids []*big.Int, amounts []*big.Int, data []byte) *contract.Txn {
	return e.c.Txn("safeBatchTransferFrom", from, to, ids, amounts, data)
}

// SafeTransferFrom sends a safeTransferFrom transaction in the solidity contract
func (e *ERC1155) SafeTransferFrom(from web3.Address, to web3.Address, id *big.Int, amount *big.Int, data []byte) *contract.Txn {
	return e.c.Txn("safeTransferFrom", from, to, id, amount, data)
}

// SetApprovalForAll sends a setApprovalForAll transaction in the solidity contract
func (e *ERC1155) SetApprovalForAll(operator web3.Address, approved bool) *contract.Txn {
	return e.c.Txn("setApprovalForAll", operator, approved)
}

// events

func (e *ERC1155) ApprovalForAllEventSig() web3.Hash {
	return e.c.ABI().Events["ApprovalForAll"].ID()
}

func (e *ERC1155) TransferBatchEventSig() web3.Hash {
	return e.c.ABI().Events["TransferBatch"].ID()
}

func (e *ERC1155) TransferSingleEventSig() web3.Hash {
	return e.c.ABI().Events["TransferSingle"].ID()
}

func (e *ERC1155) URIEventSig() web3.Hash {
	return e.c.ABI().Events["URI"].ID()
}
