// Code generated by ethgo/abigen. DO NOT EDIT.
// Hash: f173be9cb8462f7791e4b4b43cc0e3a1adb21977427d29b06bd60b0648e9dfb2
// Version: 0.1.1
package erc721

import (
	"fmt"
	"math/big"

	"github.com/umbracle/ethgo"
	"github.com/umbracle/ethgo/contract"
	"github.com/umbracle/ethgo/jsonrpc"
)

var (
	_ = big.NewInt
	_ = jsonrpc.NewClient
)

// ERC721 is a solidity contract
type ERC721 struct {
	c *contract.Contract
}

// NewERC721 creates a new instance of the contract at a specific address
func NewERC721(addr ethgo.Address, opts ...contract.ContractOption) *ERC721 {
	return &ERC721{c: contract.NewContract(addr, abiERC721, opts...)}
}

// calls

// BalanceOf calls the balanceOf method in the solidity contract
func (e *ERC721) BalanceOf(owner ethgo.Address, block ...ethgo.BlockNumber) (retval0 *big.Int, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("balanceOf", ethgo.EncodeBlock(block...), owner)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(*big.Int)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// GetApproved calls the getApproved method in the solidity contract
func (e *ERC721) GetApproved(tokenId *big.Int, block ...ethgo.BlockNumber) (retval0 ethgo.Address, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("getApproved", ethgo.EncodeBlock(block...), tokenId)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(ethgo.Address)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// IsApprovedForAll calls the isApprovedForAll method in the solidity contract
func (e *ERC721) IsApprovedForAll(owner ethgo.Address, operator ethgo.Address, block ...ethgo.BlockNumber) (retval0 bool, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("isApprovedForAll", ethgo.EncodeBlock(block...), owner, operator)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(bool)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// Name calls the name method in the solidity contract
func (e *ERC721) Name(block ...ethgo.BlockNumber) (retval0 string, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("name", ethgo.EncodeBlock(block...))
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(string)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// OwnerOf calls the ownerOf method in the solidity contract
func (e *ERC721) OwnerOf(tokenId *big.Int, block ...ethgo.BlockNumber) (retval0 ethgo.Address, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("ownerOf", ethgo.EncodeBlock(block...), tokenId)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(ethgo.Address)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// SupportsInterface calls the supportsInterface method in the solidity contract
func (e *ERC721) SupportsInterface(interfaceId [4]byte, block ...ethgo.BlockNumber) (retval0 bool, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("supportsInterface", ethgo.EncodeBlock(block...), interfaceId)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(bool)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// Symbol calls the symbol method in the solidity contract
func (e *ERC721) Symbol(block ...ethgo.BlockNumber) (retval0 string, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("symbol", ethgo.EncodeBlock(block...))
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(string)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// TokenURI calls the tokenURI method in the solidity contract
func (e *ERC721) TokenURI(tokenId *big.Int, block ...ethgo.BlockNumber) (retval0 string, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = e.c.Call("tokenURI", ethgo.EncodeBlock(block...), tokenId)
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(string)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// txns

// Approve sends a approve transaction in the solidity contract
func (e *ERC721) Approve(to ethgo.Address, tokenId *big.Int) (contract.Txn, error) {
	return e.c.Txn("approve", to, tokenId)
}

// SafeTransferFrom sends a safeTransferFrom transaction in the solidity contract
func (e *ERC721) SafeTransferFrom(from ethgo.Address, to ethgo.Address, tokenId *big.Int) (contract.Txn, error) {
	return e.c.Txn("safeTransferFrom", from, to, tokenId)
}

// SafeTransferFrom0 sends a safeTransferFrom0 transaction in the solidity contract
func (e *ERC721) SafeTransferFrom0(from ethgo.Address, to ethgo.Address, tokenId *big.Int, data []byte) (contract.Txn, error) {
	return e.c.Txn("safeTransferFrom0", from, to, tokenId, data)
}

// SetApprovalForAll sends a setApprovalForAll transaction in the solidity contract
func (e *ERC721) SetApprovalForAll(operator ethgo.Address, approved bool) (contract.Txn, error) {
	return e.c.Txn("setApprovalForAll", operator, approved)
}

// TransferFrom sends a transferFrom transaction in the solidity contract
func (e *ERC721) TransferFrom(from ethgo.Address, to ethgo.Address, tokenId *big.Int) (contract.Txn, error) {
	return e.c.Txn("transferFrom", from, to, tokenId)
}

// events

func (e *ERC721) ApprovalEventSig() ethgo.Hash {
	return e.c.GetABI().Events["Approval"].ID()
}

func (e *ERC721) ApprovalForAllEventSig() ethgo.Hash {
	return e.c.GetABI().Events["ApprovalForAll"].ID()
}

func (e *ERC721) TransferEventSig() ethgo.Hash {
	return e.c.GetABI().Events["Transfer"].ID()
}
